compact: true
directory:
  - .
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - all
quiet: true
skip-path:
  - .external_modules
  - modules
  - catalog-info.yml
baseline: .checkov.baseline
