# DO NOT CHANGE. This file is being managed from a central repository
# To know more simply visit https://github.com/honestbank/.github/blob/main/docs/about.md

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
  - repo: local
    hooks:
      - id: create-checkov-baseline
        name: Create Checkov Baseline
        entry: bash -c 'if [ ! -f .checkov.baseline ]; then echo "{}" > .checkov.baseline && touch baseline-created; fi'
        language: system
        stages: [pre-commit]
        pass_filenames: false
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 05fd71a57a467ccf5598f7e836d3af4cf9225abb  # frozen: v1.108.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
          - --tf-init-args=-upgrade
      - id: terraform_trivy
        args:
          - --args=--config=trivy.yaml
      - id: terraform_checkov
        exclude: "test/"
        args:
          - --args=--config-file __GIT_WORKING_DIR__/.checkov.yaml --baseline __GIT_WORKING_DIR__/.checkov.baseline
  - repo: local
    hooks:
      - id: delete-checkov-baseline
        name: Delete Checkov Baseline
        entry: bash -c 'if [ -f baseline-created ]; then rm .checkov.baseline && rm baseline-created; fi'
        language: system
        stages: [pre-commit]
        pass_filenames: false
  - repo: https://github.com/gitleaks/gitleaks
    rev: 2ca41cc1372d1e939a6a879f18cdc19fc1cac1ce  # frozen: v8.30.0
    hooks:
      - id: gitleaks
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: docs
        name: docs
        entry: make
        args: ["docs"]
        language: system
        pass_filenames: false
      - id: commit-msg-spell-check
        name: commit-msg-spell-check
        entry: ./spell-check.sh
        language: script
        stages: [ "commit-msg" ]
      - id: append-ticket-id
        name: Append Ticket ID to Commit Message
        entry: ./append-ticket-id.sh
        language: script
        stages: [ commit-msg ]
  # Run this at the end so that we don't end up in infinite loop
  # where the end of line fixer runs first and then the docs and fmt
  # and other hooks that modify files will break it again.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
