###
# This file contains no business logic.
# It's sole goal is to provide a way to read out the tags of the node pool, which include the ones we apply with this component + the ones Generated by Google.
###

locals {
  # includes the by GCP-managed tags
  all_primary_node_pool_tags = sort(data.google_compute_instance.first_node_pool_instance.tags)
}

data "google_compute_instance_group" "first_node_pool_instance_group" {
  depends_on = [module.node_pools]

  self_link = element(element(values(module.node_pools), 0).managed_instance_group_urls, 0)
}

data "google_compute_instance" "first_node_pool_instance" {
  self_link = tolist(data.google_compute_instance_group.first_node_pool_instance_group.instances)[0]
}
