###
# This file contains no business logic.
# The solely goal is to provide a way to read out the tags of the node pool, which include the ones we apply with this component + the ones Generated by Google.
###

locals {
  # includes the by GCP-managed tags
  primary_node_pool_all_tags = sort(data.google_compute_instance.primary_node_pool.tags)
}

data "google_compute_instance_group" "primary_node_pool" {
  depends_on = [google_container_node_pool.primary_node_pool]
  self_link  = element(google_container_node_pool.primary_node_pool.managed_instance_group_urls, 0)
}

data "google_compute_instance" "primary_node_pool" {
  self_link = sort(data.google_compute_instance_group.primary_node_pool.instances)[0]
}
