name: "Checkov GitHub Action"
permissions: read-all

on:
  pull_request:
    branches: [test, dev, qa, prod, main]

jobs:
  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create empty baseline (if needed)
        run: |
          if [ -f .checkov.baseline ]; then
            echo "⏩⏩⏩ Baseline file exists - do nothing."
          else
            echo "🆕🆕🆕 Baseline file does not exist - creating empty baseline file."
            echo "{}" >> .checkov.baseline
          fi
      - name: Output baseline contents to console
        run: |
            echo "Checkov baseline file (.checkov.baseline) contents:"
            cat .checkov.baseline
      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf # v12.1347.0
        with:
          config_file: ".checkov.yaml"
