name: repository-terratest
permissions:
  contents: write
  pull-requests: write
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  TERRATEST_GOOGLE_CREDENTIALS_NETWORK: ${{secrets.TERRATEST_GOOGLE_CREDENTIALS_NETWORK}}
  TERRATEST_GOOGLE_CREDENTIALS_COMPUTE: ${{secrets.TERRATEST_GOOGLE_CREDENTIALS_COMPUTE}}
jobs:
  repository-terratest:
    name: repository-terratest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go (1.23)
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
        id: go
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
      - name: Run terratest
        run: |
          cd test
          go mod tidy
          go mod download
          go test -v -timeout 60m
      - name: Release
        if: github.event_name == 'push'
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1
