name: "repository-checkov"
permissions: read-all

on:
  pull_request:
    branches:
      - main

jobs:
  repository-checkov:
    name: repository-checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          token: ${{ secrets.ENGINEERING_GITHUB_PERSONAL_ACCESS_TOKEN }}
      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          config_file: ".checkov.yaml"
