name: "Terraform GitHub Actions"
permissions: read-all
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  tf_version: "latest"
  tf_working_dir: "."
  TF_VAR_google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
jobs:
  terraform:
    name: "Terraform - Format, Init, Validate, Plan, Fail on Change"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init -upgrade
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
