name: "Terraform Workflow"
permissions:
  actions: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    name: terraform-internal-job
    uses: honestbank/workflows/.github/workflows/terraform.yaml@dev
    with:
      repo_name: ${{ github.event.repository.name }}
    secrets: inherit
